sudo: required
language: python
python:
  - "3.6"

services:
  - docker

env:
  - IS_LOCAL=false

branches:
  only:
    - master
    - devel

# before_install:s
#   - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
before_install:
  # linux
  - |
    wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.1.0/travis-wait-enhanced_1.1.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
    mv travis-wait-enhanced /home/travis/bin/
    travis-wait-enhanced --version

install:
  - pip install wait-for-it
  - make IS_LOCAL=$IS_LOCAL build_python

script:
  - docker run -d -p 9000:9000 -e IS_AUTOGEN_CERT="true" --name prep-node iconloop/prep-node:$(make version) 
  - travis_wait 50 docker ps -a
#   - travis-wait-enhanced --timeout=5m --print-string="Still running" --interval=5s -- curl 127.0.0.1:9000/api/v1/status/peer
  - wait-for-it --service 127.0.0.1:9000 -t 200  -- curl 127.0.0.1:9000/api/v1/status/peer
  - curl http://127.0.0.1/api/v1/status/peer
  - docker logs prep-node

