language: python
python:
  - "3.6"

services:
  - docker

env:  # env에 따라서 n개의 sendbox가 만들어지고 빌드됨
  - IS_LOCAL=false

branches:
  only:
    - master
    - devel

# before_install:s
#   - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
# before_install:
#   # linux
#   - |
#     wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.1.0/travis-wait-enhanced_1.1.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
#     mv travis-wait-enhanced /home/travis/bin/
   #  travis-wait-enhanced --version
install:
  - pip install wait-for-it
  - make IS_LOCAL=$IS_LOCAL build_python
  - docker run -d --rm -p 9000:9000 -e CREP_ROOT_HASH="0x9718f5d6d6ddb77f547ecc7113c8f1bad1bf46220512fbde356eee74a90ba47c" -e LOG_OUTPUT_TYPE="console" -e IS_AUTOGEN_CERT="true" -e PRIVATE_PATH="/private.pem" --name prep-node iconloop/prep-node:$(make version)

before_script:
  - ./src/wait-port.py -a localhost -p 9000 -t 80
  - wait-for-it --service 127.0.0.1:9000 -t 300 -- curl 127.0.0.1:9000/api/v1/status/peer
  - until curl -s localhost:9000/api/v1/status/peer; do true; sleep 1; done

script:
  - sleep 100
  - docker ps -a
#   - travis-wait-enhanced --timeout=5m --print-string="Still running" --interval=5s -- curl 127.0.0.1:9000/api/v1/status/peer
#   - wait-for-it --service 127.0.0.1:9000 -t 300  
#   - sleep 30
#  - ls -al
#  - until curl -s localhost:9000; do true; done
#  - chmod 750 ./src/wait-port.py
#   - ./src/wait-port.py -a 127.0.0.1 -p 9000 -t 80
#  - curl -vvv http://localhost:9000/api/v1/status/peer
  - curl http://localhost:9000/api/v1/status/peer | jq
  

after_failure: docker logs prep-node
